### PR TITLE
BUGFIX

### PR DESCRIPTION
**Pull request by mechanicMo**

### CODE REVIEW

**Comment by salman-monetate** [comment]
Can you build it, and check the build size on npmjs size is around 2MB. Earlier it was ~400KB.

**Comment by mechanicMo** [comment]
> Can you build it, and check the build size. On npmjs size is around 2MB, earlier it was ~400KB.

i ran the build. also, the analyze i ran created a very large file 1.4m so i deleted that too

**Review by salman-monetate — APPROVED** [review]

**Comment by mechanicMo** [comment]
@salman-monetate how does it get updated on npmjs?

**Comment by salman-monetate** [comment]
> @salman-monetate how does it get updated on npmjs?

I just published this one, `npm publish` publishes it, you might need an account for that.

**Pull request merged**
